frame: Overhaul errors, so instead of ValueError everywhere we use more specific AMQP errors
The meanings of each kind of error are as follows.
ValueError: Bad value attempted to be packed (user error).
AMQPSyntaxError: Recoverable error in unpack.
FrameError: Unrecoverable error in unpack, ie. no more frames can be unambiguously received.